### ISSUE TITLE
[CRITICAL]  Waving hand squished on safari

### ISSUE THREAD

**Issue by leinaD006** [derekvawdrey/derekvawdrey#1]
In the README.md file, the waving hand image is squished vertically and stretched horizontally, it only seems to happen on safari. This severely affects my enjoyment of your profile. Please address.

<img width="1029" alt="image" src="https://github.com/derekvawdrey/derekvawdrey/assets/77358619/79bc03f2-fa5d-449f-90ce-34cf8c3e70b8">

**Comment by algabl** [comment]
It seems like the `animated-image` tag css property `max-width` is what is causing this issue. Please confirm?

**Comment by derekvawdrey** [comment]
I've gone ahead and merged the commit. Thanks for the continual effort and maintenance of this open source repo!
